service: smart-attendance-system

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30
  environment:
    DYNAMODB_TABLE_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
    S3_BUCKET: ${self:service}-${opt:stage, self:provider.stage}-storage
    FRONTEND_URL: ${env:FRONTEND_URL, 'http://localhost:5173'}
    FROM_EMAIL: ${env:FROM_EMAIL, 'noreply@smartattendance.edu'}
    NODE_ENV: ${opt:stage, 'development'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
    - Effect: Allow
      Action:
        - rekognition:*
      Resource: "*"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - ses:VerifyEmailIdentity
      Resource: "*"

plugins:
  - serverless-localstack
  - serverless-offline

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: false
    lambda:
      mountCode: true
    docker:
      sudo: false
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3003
    timeout: 30

functions:
  # Authentication functions
  teacherRegister:
    handler: src/handlers/auth/register.handler
    events:
      - http:
          path: auth/register
          method: post
          cors: true

  teacherLogin:
    handler: src/handlers/auth/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true

  verifyEmail:
    handler: src/handlers/auth/verify-email.handler
    events:
      - http:
          path: auth/verify-email
          method: post
          cors: true

  resendVerification:
    handler: src/handlers/auth/resend-verification.handler
    events:
      - http:
          path: auth/resend-verification
          method: post
          cors: true

  # Class Management functions
  createClass:
    handler: src/handlers/classes/create-class.handler
    events:
      - http:
          path: classes
          method: post
          cors: true

  getClasses:
    handler: src/handlers/classes/get-classes.handler
    events:
      - http:
          path: classes
          method: get
          cors: true

  getClass:
    handler: src/handlers/classes/get-class.handler
    events:
      - http:
          path: classes/{classId}
          method: get
          cors: true

  updateClass:
    handler: src/handlers/classes/update-class.handler
    events:
      - http:
          path: classes/{classId}
          method: put
          cors: true

  deleteClass:
    handler: src/handlers/classes/delete-class.handler
    events:
      - http:
          path: classes/{classId}
          method: delete
          cors: true

  # Session Management functions
  createSession:
    handler: src/handlers/sessions/create-session.handler
    events:
      - http:
          path: sessions
          method: post
          cors: true

  getSessionsByClass:
    handler: src/handlers/sessions/get-sessions.handler
    events:
      - http:
          path: classes/{classId}/sessions
          method: get
          cors: true

  getSession:
    handler: src/handlers/sessions/get-session.handler
    events:
      - http:
          path: sessions/{sessionId}
          method: get
          cors: true

  endSession:
    handler: src/handlers/sessions/end-session.handler
    events:
      - http:
          path: sessions/{sessionId}/end
          method: post
          cors: true

  # Student Management functions (teacher dashboard only)
  # NOTE: Student registration removed - students auto-register via QR attendance

  getStudentsByClass:
    handler: src/handlers/students/get-students.handler
    events:
      - http:
          path: classes/{classId}/students
          method: get
          cors: true

  getStudent:
    handler: src/handlers/students/get-student.handler
    events:
      - http:
          path: students/{studentId}
          method: get
          cors: true

  # Attendance functions (teacher dashboard - viewing only)
  # NOTE: Manual attendance marking removed - all attendance via QR codes now

  getSessionAttendance:
    handler: src/handlers/attendance/get-session-attendance.handler
    events:
      - http:
          path: sessions/{sessionId}/attendance
          method: get
          cors: true

  getStudentAttendance:
    handler: src/handlers/attendance/get-student-attendance.handler
    events:
      - http:
          path: students/{studentId}/attendance
          method: get
          cors: true

  # Student-facing public endpoints (no authentication required)
  getSessionInfo:
    handler: src/handlers/attendance/get-session-info.handler
    events:
      - http:
          path: api/student/session/{sessionId}
          method: get
          cors: true

  submitStudentAttendance:
    handler: src/handlers/attendance/submit-attendance.handler
    events:
      - http:
          path: api/student/attendance
          method: post
          cors: true

resources:
  Resources:
    # DynamoDB Tables
    TeachersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Teachers
        AttributeDefinitions:
          - AttributeName: teacherId
            AttributeType: S
        KeySchema:
          - AttributeName: teacherId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    ClassesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Classes
        AttributeDefinitions:
          - AttributeName: classId
            AttributeType: S
        KeySchema:
          - AttributeName: classId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    SessionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Sessions
        AttributeDefinitions:
          - AttributeName: sessionId
            AttributeType: S
        KeySchema:
          - AttributeName: sessionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    StudentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Students
        AttributeDefinitions:
          - AttributeName: studentId
            AttributeType: S
        KeySchema:
          - AttributeName: studentId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    AttendanceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Attendance
        AttributeDefinitions:
          - AttributeName: attendanceId
            AttributeType: S
        KeySchema:
          - AttributeName: attendanceId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    # S3 Bucket for face images
    FaceImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: smart-attendance-faces
        VersioningConfiguration:
          Status: Enabled
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
